// `mora_phonemes` is generated by scripts/gen_ja_map.py from misaki ja.py (Apache-2.0, hexgrad/misaki).
// Everything below it is hand-written.
pub(crate) fn mora_phonemes(mora: &str) -> Option<&'static str> {
    match mora {
        "ァ" => Some("a"),
        "ア" => Some("a"),
        "ィ" => Some("i"),
        "イ" => Some("i"),
        "イェ" => Some("je"),
        "ゥ" => Some("u"),
        "ウ" => Some("u"),
        "ウィ" => Some("wi"),
        "ウゥ" => Some("wu"),
        "ウェ" => Some("we"),
        "ウォ" => Some("wo"),
        "ェ" => Some("e"),
        "エ" => Some("e"),
        "ォ" => Some("o"),
        "オ" => Some("o"),
        "カ" => Some("ka"),
        "ガ" => Some("ga"),
        "キ" => Some("ki"),
        "キィ" => Some("ᶄi"),
        "キェ" => Some("ᶄe"),
        "キャ" => Some("ᶄa"),
        "キュ" => Some("ᶄu"),
        "キョ" => Some("ᶄo"),
        "ギ" => Some("gi"),
        "ギィ" => Some("ᶃi"),
        "ギェ" => Some("ᶃe"),
        "ギャ" => Some("ᶃa"),
        "ギュ" => Some("ᶃu"),
        "ギョ" => Some("ᶃo"),
        "ク" => Some("ku"),
        "クァ" => Some("Ka"),
        "クィ" => Some("Ki"),
        "クゥ" => Some("Ku"),
        "クェ" => Some("Ke"),
        "クォ" => Some("Ko"),
        "クヮ" => Some("Ka"),
        "グ" => Some("gu"),
        "グァ" => Some("Ga"),
        "グィ" => Some("Gi"),
        "グゥ" => Some("Gu"),
        "グェ" => Some("Ge"),
        "グォ" => Some("Go"),
        "グヮ" => Some("Ga"),
        "ケ" => Some("ke"),
        "ゲ" => Some("ge"),
        "コ" => Some("ko"),
        "ゴ" => Some("go"),
        "サ" => Some("sa"),
        "ザ" => Some("za"),
        "シ" => Some("ɕi"),
        "シェ" => Some("ɕe"),
        "シャ" => Some("ɕa"),
        "シュ" => Some("ɕu"),
        "ショ" => Some("ɕo"),
        "ジ" => Some("ʥi"),
        "ジェ" => Some("ʥe"),
        "ジャ" => Some("ʥa"),
        "ジュ" => Some("ʥu"),
        "ジョ" => Some("ʥo"),
        "ス" => Some("su"),
        "スィ" => Some("si"),
        "ズ" => Some("zu"),
        "ズィ" => Some("zi"),
        "セ" => Some("se"),
        "ゼ" => Some("ze"),
        "ソ" => Some("so"),
        "ゾ" => Some("zo"),
        "タ" => Some("ta"),
        "ダ" => Some("da"),
        "チ" => Some("ʨi"),
        "チェ" => Some("ʨe"),
        "チャ" => Some("ʨa"),
        "チュ" => Some("ʨu"),
        "チョ" => Some("ʨo"),
        "ヂ" => Some("ʥi"),
        "ヂェ" => Some("ʥe"),
        "ヂャ" => Some("ʥa"),
        "ヂュ" => Some("ʥu"),
        "ヂョ" => Some("ʥo"),
        "ッ" => Some("ʔ"),
        "ツ" => Some("ʦu"),
        "ツァ" => Some("ʦa"),
        "ツィ" => Some("ʦi"),
        "ツェ" => Some("ʦe"),
        "ツォ" => Some("ʦo"),
        "ヅ" => Some("zu"),
        "テ" => Some("te"),
        "ティ" => Some("ti"),
        "テェ" => Some("ƫe"),
        "テャ" => Some("ƫa"),
        "テュ" => Some("ƫu"),
        "テョ" => Some("ƫo"),
        "デ" => Some("de"),
        "ディ" => Some("di"),
        "デェ" => Some("ᶁe"),
        "デャ" => Some("ᶁa"),
        "デュ" => Some("ᶁu"),
        "デョ" => Some("ᶁo"),
        "ト" => Some("to"),
        "トゥ" => Some("tu"),
        "ド" => Some("do"),
        "ドゥ" => Some("du"),
        "ナ" => Some("na"),
        "ニ" => Some("ni"),
        "ニィ" => Some("ɲi"),
        "ニェ" => Some("ɲe"),
        "ニャ" => Some("ɲa"),
        "ニュ" => Some("ɲu"),
        "ニョ" => Some("ɲo"),
        "ヌ" => Some("nu"),
        "ネ" => Some("ne"),
        "ノ" => Some("no"),
        "ハ" => Some("ha"),
        "バ" => Some("ba"),
        "パ" => Some("pa"),
        "ヒ" => Some("hi"),
        "ヒィ" => Some("çi"),
        "ヒェ" => Some("çe"),
        "ヒャ" => Some("ça"),
        "ヒュ" => Some("çu"),
        "ヒョ" => Some("ço"),
        "ビ" => Some("bi"),
        "ビィ" => Some("ᶀi"),
        "ビェ" => Some("ᶀe"),
        "ビャ" => Some("ᶀa"),
        "ビュ" => Some("ᶀu"),
        "ビョ" => Some("ᶀo"),
        "ピ" => Some("pi"),
        "ピィ" => Some("ᶈi"),
        "ピェ" => Some("ᶈe"),
        "ピャ" => Some("ᶈa"),
        "ピュ" => Some("ᶈu"),
        "ピョ" => Some("ᶈo"),
        "フ" => Some("fu"),
        "ファ" => Some("fa"),
        "フィ" => Some("fi"),
        "フェ" => Some("fe"),
        "フォ" => Some("fo"),
        "ブ" => Some("bu"),
        "プ" => Some("pu"),
        "ヘ" => Some("he"),
        "ベ" => Some("be"),
        "ペ" => Some("pe"),
        "ホ" => Some("ho"),
        "ボ" => Some("bo"),
        "ポ" => Some("po"),
        "マ" => Some("ma"),
        "ミ" => Some("mi"),
        "ミィ" => Some("ᶆi"),
        "ミェ" => Some("ᶆe"),
        "ミャ" => Some("ᶆa"),
        "ミュ" => Some("ᶆu"),
        "ミョ" => Some("ᶆo"),
        "ム" => Some("mu"),
        "メ" => Some("me"),
        "モ" => Some("mo"),
        "ャ" => Some("ja"),
        "ヤ" => Some("ja"),
        "ュ" => Some("ju"),
        "ユ" => Some("ju"),
        "ョ" => Some("jo"),
        "ヨ" => Some("jo"),
        "ラ" => Some("ra"),
        "リ" => Some("ri"),
        "リィ" => Some("ᶉi"),
        "リェ" => Some("ᶉe"),
        "リャ" => Some("ᶉa"),
        "リュ" => Some("ᶉu"),
        "リョ" => Some("ᶉo"),
        "ル" => Some("ru"),
        "レ" => Some("re"),
        "ロ" => Some("ro"),
        "ヮ" => Some("wa"),
        "ワ" => Some("wa"),
        "ヰ" => Some("i"),
        "ヱ" => Some("e"),
        "ヲ" => Some("o"),
        "ン" => Some("ɴ"),
        "ヴ" => Some("vu"),
        "ヴァ" => Some("va"),
        "ヴィ" => Some("vi"),
        "ヴェ" => Some("ve"),
        "ヴォ" => Some("vo"),
        "ヴャ" => Some("ᶀa"),
        "ヴュ" => Some("ᶀu"),
        "ヴョ" => Some("ᶀo"),
        "ヵ" => Some("ka"),
        "ヶ" => Some("ke"),
        "ヷ" => Some("va"),
        "ヸ" => Some("vi"),
        "ヹ" => Some("ve"),
        "ヺ" => Some("vo"),
        "ー" => Some("ː"),
        _ => None,
    }
}

pub(crate) fn pron_to_moras(pron: &str) -> Vec<String> {
    pron.chars()
        .filter(|c| mora_phonemes(c.encode_utf8(&mut [0; 4])).is_some())
        .fold(Vec::new(), |mut moras: Vec<String>, c| {
            match moras.last_mut() {
                Some(last) if mora_phonemes(&format!("{last}{c}")).is_some() => last.push(c),
                _ => moras.push(c.to_string()),
            }
            moras
        })
}

pub(crate) fn moras_to_phonemes(moras: &[String]) -> String {
    moras
        .iter()
        .filter_map(|mora| mora_phonemes(mora))
        .collect()
}

pub(crate) fn is_tail(c: char) -> bool {
    matches!(c, 'a' | 'e' | 'i' | 'o' | 'u' | 'ʔ' | 'ɴ' | 'ː')
}

/// Maps misaki phoneme symbols absent from Kokoro's vocab to vocab symbols; the tokenizer silently drops unknown symbols.
pub(crate) fn fit_to_vocab(phonemes: &str) -> String {
    phonemes
        .chars()
        .map(|c| match c {
            'g' => "ɡ".to_string(),
            'G' => "ɡᵝ".to_string(),
            'K' => "kᵝ".to_string(),
            'ƫ' => "tʲ".to_string(),
            'ᶀ' => "bʲ".to_string(),
            'ᶁ' => "dʲ".to_string(),
            'ᶃ' => "ɡʲ".to_string(),
            'ᶄ' => "kʲ".to_string(),
            'ᶆ' => "mʲ".to_string(),
            'ᶈ' => "pʲ".to_string(),
            'ᶉ' => "rʲ".to_string(),
            other => other.to_string(),
        })
        .collect()
}

#[cfg(test)]
mod tests {
    use super::*;

    fn moras(pron: &str) -> Vec<String> {
        pron_to_moras(pron)
    }

    #[test]
    fn single_kana_maps_to_phonemes() {
        assert_eq!(mora_phonemes("カ"), Some("ka"));
        assert_eq!(mora_phonemes("シ"), Some("ɕi"));
        assert_eq!(mora_phonemes("ッ"), Some("ʔ"));
        assert_eq!(mora_phonemes("ン"), Some("ɴ"));
        assert_eq!(mora_phonemes("ー"), Some("ː"));
    }

    #[test]
    fn small_kana_combine_with_the_previous_mora() {
        assert_eq!(moras("キャ"), vec!["キャ"]);
        assert_eq!(moras("シュッパツ"), vec!["シュ", "ッ", "パ", "ツ"]);
    }

    #[test]
    fn non_kana_is_dropped() {
        assert_eq!(moras("ア、イ’"), vec!["ア", "イ"]);
    }

    #[test]
    fn moras_join_into_phonemes() {
        assert_eq!(moras_to_phonemes(&moras("コンニチワ")), "koɴniʨiwa");
    }

    #[test]
    fn tails_are_the_final_chars_of_table_values() {
        assert!(is_tail('a') && is_tail('ɴ') && is_tail('ː') && is_tail('ʔ'));
        assert!(!is_tail('k') && !is_tail(' '));
    }

    fn all_table_symbols() -> std::collections::BTreeSet<char> {
        let kana: Vec<char> = ('\u{30A1}'..='\u{30F6}').chain(['ー']).collect();
        let singles = kana.iter().map(|c| c.to_string());
        let pairs = kana
            .iter()
            .flat_map(|a| kana.iter().map(move |b| format!("{a}{b}")));
        singles
            .chain(pairs)
            .filter_map(|mora| mora_phonemes(&mora))
            .flat_map(|phonemes| fit_to_vocab(phonemes).chars().collect::<Vec<_>>())
            .collect()
    }

    #[test]
    fn every_table_symbol_exists_in_the_kokoro_vocab() {
        let Some(path) = std::env::var_os("DENGJEN_KOKORO_VOCAB") else {
            return;
        };
        let vocab = crate::Vocab::load(std::path::Path::new(&path)).unwrap();
        let missing: Vec<char> = all_table_symbols()
            .into_iter()
            .filter(|c| vocab.tokenize(&c.to_string()).is_empty())
            .collect();
        assert!(
            missing.is_empty(),
            "symbols missing from the vocab: {missing:?}"
        );
    }

    #[test]
    fn the_symbol_collector_sees_the_special_misaki_symbols() {
        let symbols = all_table_symbols();
        assert!(symbols.contains(&'ʨ') && symbols.contains(&'ɴ') && symbols.contains(&'ː'));
    }

    #[test]
    fn fit_to_vocab_replaces_symbols_the_vocab_lacks() {
        assert_eq!(fit_to_vocab("ga"), "ɡa");
        assert_eq!(fit_to_vocab("ᶄo"), "kʲo");
        assert_eq!(fit_to_vocab("Ka"), "kᵝa");
        assert_eq!(fit_to_vocab("Ga"), "ɡᵝa");
        assert_eq!(fit_to_vocab("ᶉa"), "rʲa");
    }

    #[test]
    fn fit_to_vocab_leaves_vocab_symbols_alone() {
        assert_eq!(fit_to_vocab("koɴniʨiwa. ʥuː"), "koɴniʨiwa. ʥuː");
    }
}
