import re, sys

src = open(sys.argv[1], encoding="utf-8").read()
entries = {}
for m in re.finditer(r"^((?:chr\(\d+\)\+?)+): '([^']+)'", src, re.M):
    key = "".join(chr(int(n)) for n in re.findall(r"chr\((\d+)\)", m.group(1)))
    entries[key] = m.group(2)
entries.update({"ッ": "ʔ", "ン": "ɴ", "ー": "ː"})
assert len(entries) == 193, len(entries)
print("// `mora_phonemes` is generated by scripts/gen_ja_map.py from misaki ja.py (Apache-2.0, hexgrad/misaki).")
print("// Everything below it is hand-written.")
print("pub(crate) fn mora_phonemes(mora: &str) -> Option<&'static str> {")
print("    match mora {")
for k in sorted(entries):
    print(f'        "{k}" => Some("{entries[k]}"),')
print("        _ => None,")
print("    }")
print("}")
